name: nnunet_env_v1
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python[version='<3.12']
  - autopep8
  - beautifulsoup4
  - black
  - clearml
  - dicom2nifti
  - dominate
  - einops
  - fire
  - fpdf2
  - gdown
  - ignite
  - ipywidgets
  - isort
  - itk
  - jupyterlab
  - keras
  - lightning
  - matplotlib
  - mlflow
  - monai
  - nbconvert
  - nbformat
  - nibabel
  - nilearn
  - numpy
  - opencv
  - pandas
  - paramiko
  - patool
  - pillow
  - pingouin
  - plotly
  - pydicom
  - pynetdicom
  - pynrrd
  - python-dotenv
  - python-lmdb
  - python-pdfkit
  - python-pptx
  - pytorch[version='>2']
  - pytorch-cuda=12.4
  - pyyaml
  - requests
  - rich
  - scikit-image
  - scikit-learn
  - scikit-multilearn
  - scipy
  - scp
  - seaborn
  - setuptools
  - simpleitk
  - six
  - statsmodels
  - stdlib-list
  - tensorboard
  - tensorflow[version='>2.12']
  - termcolor
  - torchvision
  - tqdm
  - transformers
  - dill[version='<0.3.9']
  - pip
  - pip:
      - -e /data/irf/ai/rustadmd/dmist-nnunet-fork[dev]
      - pyradiomics
      - git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588
      - git+https://github.com/Project-MONAI/MetricsReloaded@monai-support#egg=MetricsReloaded
      - git+https://github.com/MIC-DKFZ/acvl_utils.git
      - git+https://github.com/MIC-DKFZ/dynamic-network-architectures.git
      - git+https://github.com/FabianIsensee/hiddenlayer.git
      - git+https://github.com/wasserth/TotalSegmentator.git
