name: nnunet_min_env_v1
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - autopep8
  - black
  - dicom2nifti
  - einops
  - fpdf2
  - ignite
  - ipywidgets
  - isort
  - jupyterlab
  - keras
  - lightning
  - matplotlib
  - monai
  - nbconvert
  - nbformat
  - nibabel
  - numpy
  - patool
  - pillow
  - pingouin
  - plotly
  - pydicom
  - python-dotenv
  - python-pptx
  - pytorch[version='>2']
  - pytorch-cuda=12.4
  - pyyaml
  - requests
  - scikit-image
  - scikit-learn
  - scikit-multilearn
  - scipy
  - seaborn
  - setuptools
  - simpleitk
  - six
  - statsmodels
  - tensorboard
  - tensorflow[version='>2.12']
  - termcolor
  - threadpoolctl
  - tifffile
  - torchvision
  - tqdm
  # optional packages taken from nnunet_monai_env_v1.yml
  - flake8-bugbear
  - flake8-comprehensions
  - flake8
  - h5py
  - huggingface_hub
  - imagecodecs
  - itk
  - jsonschema
  - ninja
  - pandas
  - pep8-naming
  - pycodestyle
  - pytype
  - ruff
  - tensorboardX
  - typeguard
  - types-PyYAML
  - types-setuptools
  # pandas optional deps
  - adbc-driver-postgresql # pandas optional dep
  - adbc-driver-sqlite # pandas optional dep
  - blosc # pandas optional dep
  - bottleneck # pandas optional dep
  - fastparquet # pandas optional dep
  - fsspec # pandas optional dep
  - gcsfs # pandas optional dep
  - html5lib # pandas optional dep
  - jinja2 # pandas optional dep
  - lxml # pandas optional dep
  - numba # pandas optional dep
  - numexpr # pandas optional dep
  - odfpy # pandas optional dep
  - openpyxl # pandas optional dep
  - pandas-gbq # pandas optional dep
  - psycopg2 # pandas optional dep
  - pyarrow # pandas optional dep
  - pymysql # pandas optional dep
  - pyqt # pandas optional dep
  - pyreadstat # pandas optional dep
  - pytables # pandas optional dep
  - python-calamine # pandas optional dep
  - pyxlsb # pandas optional dep
  - qtpy # pandas optional dep
  - s3fs # pandas optional dep
  - sqlalchemy # pandas optional dep
  - tabulate # pandas optional dep
  - xarray # pandas optional dep
  - xlrd # pandas optional dep
  - xlsxwriter # pandas optional dep
  - zlib # pandas optional dep
  - zstandard # pandas optional dep
  - pip
  - pip:
      - -e /data/irf/ai/rustadmd/dmist-nnunet-fork[dev]
      - pyradiomics
      - git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588
      - git+https://github.com/Project-MONAI/MetricsReloaded@monai-support#egg=MetricsReloaded
      - git+https://github.com/MIC-DKFZ/acvl_utils.git
      - git+https://github.com/MIC-DKFZ/dynamic-network-architectures.git
      - git+https://github.com/FabianIsensee/hiddenlayer.git
      - git+https://github.com/wasserth/TotalSegmentator.git
